export { default as ProfilePage } from './ProfilePage'
export { default as LoginPage } from './LoginPage'
export { default as MyVotesPage } from './MyVotesPage'
export { default as HistoryPage } from './HistoryPage'
export { default as EditProfilePage } from './EditProfilePage'
